CREATE OR ALTER PROC FI_SP_ConsCliente  
    @ID BIGINT = NULL  
AS  
BEGIN  
    IF @ID IS NULL OR @ID = 0  
    BEGIN
        SELECT NOME, SOBRENOME, NACIONALIDADE, CEP, CPF, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, ID 
        FROM CLIENTES WITH(NOLOCK);  
    END
    ELSE  
    BEGIN
        SELECT NOME, SOBRENOME, NACIONALIDADE, CEP, CPF, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, ID 
        FROM CLIENTES WITH(NOLOCK) 
        WHERE ID = @ID;  
    END
END
